Add functionality to edit user profile details.
Front-end code is added to profile.ejs.
The form will collect user data and send an ajax request to the server.
The ajax request is processed under "user/update-profile" route.
This is a temp commit to track down an error that keeps the app crashing:

events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (Incorrect arguments)
    at Function.emit (events.js:163:17)
    at Query.<anonymous> (node_modules\mongoose\lib\model.js:3921:13)
    at node_modules\kareem\index.js:273:21
    at node_modules\kareem\index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)